server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbusers?createDatabaseIfNotExist=true&verifyServerCertificate=false&useSSL=false&requireSSL=false&serverTimezone=Asia/Irkutsk&useLegacyDatetimeCode=false
    username: root
    password: root
  jpa:
    properties:
      hiber
